import type { User, Project, Hackathon, Pledge, ActivityItem } from './types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    uid: 'LP-001-AFR-KE',
    email: 'amina.okonkwo@example.com',
    name: 'Amina Okonkwo',
    role: 'builder',
    verificationLevel: 'level2',
    walletAddress: 'addr1q9...xyz',
    country: 'Kenya',
    bio: 'Full-stack developer passionate about FinTech solutions for Africa',
    hackathonsAttended: ['hack-1', 'hack-2', 'hack-3'],
    hackathonsWon: ['hack-1', 'hack-3'],
    collaborations: [
      {
        projectId: 'proj-1',
        projectName: 'PayFlow Africa',
        teamMembers: [
          { userId: 'user-1', name: 'Amina Okonkwo', gender: 'female' },
          { userId: 'user-3', name: 'Kwame Asante', gender: 'male' },
        ],
        result: 'win',
        hackathonId: 'hack-1',
      },
    ],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    uid: 'LP-002-AFR-NG',
    email: 'chidi.eze@example.com',
    name: 'Chidi Eze',
    role: 'investor',
    verificationLevel: 'level2',
    walletAddress: 'addr1q8...abc',
    country: 'Nigeria',
    bio: 'Angel investor focused on African startups',
    hackathonsAttended: [],
    hackathonsWon: [],
    collaborations: [],
    createdAt: '2024-02-20T14:30:00Z',
  },
  {
    id: 'user-3',
    uid: 'LP-003-AFR-KE',
    email: 'kwame.asante@example.com',
    name: 'Kwame Asante',
    role: 'builder',
    verificationLevel: 'level1',
    country: 'Kenya',
    bio: 'Product designer and UX researcher',
    hackathonsAttended: ['hack-1', 'hack-2'],
    hackathonsWon: ['hack-1'],
    collaborations: [],
    createdAt: '2024-01-20T09:00:00Z',
  },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'PayFlow Africa',
    tagline: 'Seamless cross-border payments for African businesses',
    vision: 'To become the payment infrastructure backbone for intra-African trade',
    problem: 'Cross-border payments in Africa are slow, expensive, and unreliable, costing businesses up to 15% in fees and delays.',
    solution: 'A blockchain-based payment rail using stablecoins to enable instant, low-cost transfers across African borders.',
    stage: 'early_users',
    sector: 'fintech',
    origin: 'hackathon',
    hackathonId: 'hack-1',
    hackathonName: 'AfroTech Hackathon 2024',
    fundingAsk: 50000,
    fundingRaised: 12500,
    team: [
      { userId: 'user-1', name: 'Amina Okonkwo', gender: 'female' },
      { userId: 'user-3', name: 'Kwame Asante', gender: 'male' },
    ],
    leaderId: 'user-1',
    metrics: {
      users: 1250,
      revenue: 2500,
      growth: 45,
    },
    stageHistory: [
      { from: 'hackathon_winner', to: 'validated_prototype', date: '2024-02-01' },
      { from: 'validated_prototype', to: 'mvp_development', date: '2024-04-15' },
      { from: 'mvp_development', to: 'early_users', date: '2024-07-01' },
    ],
    communityActivity: 85,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-09-10T16:00:00Z',
  },
  {
    id: 'proj-2',
    name: 'FarmLink',
    tagline: 'Connecting smallholder farmers directly to markets',
    vision: 'Eliminating middlemen to double farmer incomes across Africa',
    problem: 'Smallholder farmers lose up to 40% of their potential income to intermediaries and lack market access.',
    solution: 'A mobile-first marketplace connecting farmers directly to buyers with integrated logistics and financing.',
    stage: 'mvp_development',
    sector: 'agritech',
    origin: 'hackathon',
    hackathonId: 'hack-2',
    hackathonName: 'Green Innovation Summit',
    fundingAsk: 75000,
    fundingRaised: 0,
    team: [
      { userId: 'user-4', name: 'Fatou Diallo', gender: 'female' },
      { userId: 'user-5', name: 'Olumide Johnson', gender: 'male' },
    ],
    leaderId: 'user-4',
    metrics: {
      users: 320,
      growth: 28,
    },
    stageHistory: [
      { from: 'hackathon_winner', to: 'validated_prototype', date: '2024-05-01' },
      { from: 'validated_prototype', to: 'mvp_development', date: '2024-08-01' },
    ],
    communityActivity: 62,
    createdAt: '2024-04-20T08:00:00Z',
    updatedAt: '2024-09-05T12:00:00Z',
  },
  {
    id: 'proj-3',
    name: 'HealthBridge',
    tagline: 'AI-powered diagnostics for rural clinics',
    vision: 'Bringing specialist-level diagnostics to every village clinic in Africa',
    problem: 'Rural areas have 1 doctor per 50,000 people, leading to delayed diagnoses and preventable deaths.',
    solution: 'AI diagnostic tool that works offline on basic smartphones, trained on African patient data.',
    stage: 'fundraising',
    sector: 'healthtech',
    origin: 'independent',
    fundingAsk: 150000,
    fundingRaised: 45000,
    team: [
      { userId: 'user-6', name: 'Dr. Ngozi Adichie', gender: 'female' },
      { userId: 'user-7', name: 'Emmanuel Nkrumah', gender: 'male' },
      { userId: 'user-8', name: 'Sarah Wanjiku', gender: 'female' },
    ],
    leaderId: 'user-6',
    metrics: {
      users: 45,
      researchOutput: '3 peer-reviewed papers',
    },
    stageHistory: [
      { from: 'validated_prototype', to: 'mvp_development', date: '2024-03-01' },
      { from: 'mvp_development', to: 'early_users', date: '2024-06-01' },
      { from: 'early_users', to: 'fundraising', date: '2024-09-01' },
    ],
    communityActivity: 91,
    createdAt: '2024-02-10T15:00:00Z',
    updatedAt: '2024-09-12T09:00:00Z',
  },
  {
    id: 'proj-4',
    name: 'EduPesa',
    tagline: 'Micro-scholarships powered by community',
    vision: 'Making quality education accessible through community-funded micro-scholarships',
    problem: '60% of African youth cannot afford secondary education despite strong academic potential.',
    solution: 'Crowdfunded micro-scholarship platform with milestone-based releases and mentorship matching.',
    stage: 'funded',
    sector: 'edtech',
    origin: 'hackathon',
    hackathonId: 'hack-3',
    hackathonName: 'Education for All Hackathon',
    fundingAsk: 100000,
    fundingRaised: 100000,
    team: [
      { userId: 'user-9', name: 'Grace Mwangi', gender: 'female' },
    ],
    leaderId: 'user-9',
    metrics: {
      users: 2800,
      revenue: 15000,
      growth: 120,
    },
    stageHistory: [
      { from: 'hackathon_winner', to: 'validated_prototype', date: '2023-06-01' },
      { from: 'validated_prototype', to: 'mvp_development', date: '2023-09-01' },
      { from: 'mvp_development', to: 'early_users', date: '2024-01-01' },
      { from: 'early_users', to: 'revenue', date: '2024-04-01' },
      { from: 'revenue', to: 'fundraising', date: '2024-06-01' },
      { from: 'fundraising', to: 'funded', date: '2024-08-15' },
    ],
    communityActivity: 95,
    createdAt: '2023-05-01T12:00:00Z',
    updatedAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'proj-5',
    name: 'SolarGrid',
    tagline: 'Decentralized solar energy trading',
    vision: 'Creating peer-to-peer energy markets for off-grid communities',
    problem: '600M Africans lack reliable electricity, stunting economic development.',
    solution: 'Blockchain-based platform for trading excess solar energy between neighbors.',
    stage: 'validated_prototype',
    sector: 'cleantech',
    origin: 'hackathon',
    hackathonId: 'hack-2',
    hackathonName: 'Green Innovation Summit',
    fundingAsk: 200000,
    fundingRaised: 0,
    team: [
      { userId: 'user-10', name: 'Ibrahim Musa', gender: 'male' },
      { userId: 'user-11', name: 'Aisha Bello', gender: 'female' },
    ],
    leaderId: 'user-10',
    metrics: {},
    stageHistory: [
      { from: 'hackathon_winner', to: 'validated_prototype', date: '2024-08-01' },
    ],
    communityActivity: 45,
    createdAt: '2024-07-15T14:00:00Z',
    updatedAt: '2024-09-08T11:00:00Z',
  },
  {
    id: 'proj-6',
    name: 'Legacy Archive',
    tagline: 'Preserving African oral histories',
    vision: 'Digitizing and preserving 10,000 oral histories before they are lost',
    problem: 'Rich oral traditions are being lost as elders pass without documentation.',
    solution: 'AI-powered audio transcription and translation with community curation.',
    stage: 'archived',
    sector: 'research',
    origin: 'independent',
    fundingAsk: 30000,
    fundingRaised: 8000,
    team: [
      { userId: 'user-12', name: 'Prof. Ade Oluwa', gender: 'male' },
    ],
    leaderId: 'user-12',
    metrics: {
      researchOutput: '500 histories archived',
    },
    stageHistory: [
      { from: 'validated_prototype', to: 'early_users', date: '2023-03-01' },
      { from: 'early_users', to: 'archived', date: '2024-06-01' },
    ],
    communityActivity: 12,
    createdAt: '2022-11-01T10:00:00Z',
    updatedAt: '2024-06-01T16:00:00Z',
  },
];

// Mock Hackathons (HackQuest-style: image, totalPrize, techStack, level, eventType, status)
export const mockHackathons: Hackathon[] = [
  {
    id: 'hack-1',
    name: 'AfroTech Hackathon 2024',
    description: 'The largest fintech hackathon in East Africa, bringing together 500+ builders to solve financial inclusion challenges.',
    startDate: '2024-01-10',
    endDate: '2024-01-12',
    location: 'Nairobi, Kenya',
    sponsors: [
      { name: 'Cardano Foundation', tier: 'platinum' },
      { name: 'Safaricom', tier: 'gold' },
      { name: 'KCB Bank', tier: 'silver' },
    ],
    winners: [
      { projectId: 'proj-1', projectName: 'PayFlow Africa', prize: '₳10,000 + Incubation', rank: 1, advancedToLaunchPad: true },
    ],
    participants: 532,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1540575467063-178bf50e2f0e?w=600&h=320&fit=crop',
    totalPrize: '10,000USD',
    techStack: ['Solidity', 'React', 'Node.js'],
    level: 'general',
    eventType: 'hybrid',
  },
  {
    id: 'hack-2',
    name: 'Green Innovation Summit',
    description: 'Tackling climate challenges through technology. Focus on AgriTech, CleanTech, and sustainable solutions.',
    startDate: '2024-04-15',
    endDate: '2024-04-17',
    location: 'Lagos, Nigeria',
    sponsors: [
      { name: 'African Development Bank', tier: 'platinum' },
      { name: 'Total Energies', tier: 'gold' },
    ],
    winners: [
      { projectId: 'proj-2', projectName: 'FarmLink', prize: '₳8,000 + Mentorship', rank: 1, advancedToLaunchPad: true },
      { projectId: 'proj-5', projectName: 'SolarGrid', prize: '₳5,000', rank: 2, advancedToLaunchPad: true },
    ],
    participants: 380,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=600&h=320&fit=crop',
    totalPrize: '13,000USD',
    techStack: ['All'],
    level: 'general',
    eventType: 'hybrid',
  },
  {
    id: 'hack-3',
    name: 'Education for All Hackathon',
    description: 'Building solutions to democratize access to quality education across the continent.',
    startDate: '2023-05-20',
    endDate: '2023-05-22',
    location: 'Virtual (Pan-African)',
    sponsors: [
      { name: 'Mastercard Foundation', tier: 'platinum' },
      { name: 'Microsoft Africa', tier: 'gold' },
    ],
    winners: [
      { projectId: 'proj-4', projectName: 'EduPesa', prize: '₳15,000 + AWS Credits', rank: 1, advancedToLaunchPad: true },
    ],
    participants: 720,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=320&fit=crop',
    totalPrize: '15,000USD',
    techStack: ['Python', 'React'],
    level: 'general',
    eventType: 'online',
  },
  {
    id: 'hack-4',
    name: 'HealthTech Africa 2025',
    description: 'Innovating healthcare delivery for the next billion patients.',
    startDate: '2025-02-14',
    endDate: '2025-02-16',
    location: 'Accra, Ghana',
    sponsors: [
      { name: 'Bill & Melinda Gates Foundation', tier: 'platinum' },
      { name: 'WHO Africa', tier: 'gold' },
    ],
    winners: [],
    participants: 0,
    status: 'upcoming',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1f?w=600&h=320&fit=crop',
    totalPrize: '50,000USD',
    techStack: ['All'],
    level: 'general',
    eventType: 'hybrid',
    recommended: true,
  },
  {
    id: 'hack-5',
    name: 'DeFi Buildathon 2025',
    description: 'Build the next generation of decentralized finance. Real yield, real builders.',
    startDate: '2025-01-15',
    endDate: '2025-02-28',
    location: 'Online',
    sponsors: [
      { name: 'Cardano Foundation', tier: 'platinum' },
      { name: 'EMURGO', tier: 'gold' },
    ],
    winners: [],
    participants: 78,
    status: 'active',
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=600&h=320&fit=crop',
    totalPrize: '25,000USD',
    techStack: ['Solidity', 'Rust', 'Plutus'],
    level: 'general',
    eventType: 'online',
    recommended: true,
  },
  {
    id: 'hack-6',
    name: 'Climate Solutions Hack',
    description: 'Solving real world problems with real world assets. Voting open.',
    startDate: '2025-01-01',
    endDate: '2025-01-20',
    location: 'Online',
    sponsors: [{ name: 'UNEP', tier: 'platinum' }],
    winners: [],
    participants: 180,
    status: 'judging',
    image: 'https://images.unsplash.com/photo-1569163138752-1a038c416c5e?w=600&h=320&fit=crop',
    totalPrize: '35,000USD',
    techStack: ['All'],
    level: 'general',
    eventType: 'online',
  },
];

// Mock Pledges
export const mockPledges: Pledge[] = [
  {
    id: 'pledge-1',
    investorId: 'user-2',
    projectId: 'proj-1',
    amount: 5000,
    status: 'confirmed',
    createdAt: '2024-08-01T10:00:00Z',
  },
  {
    id: 'pledge-2',
    investorId: 'user-2',
    projectId: 'proj-3',
    amount: 10000,
    status: 'pending',
    createdAt: '2024-09-10T15:00:00Z',
  },
];

// Mock Activity Feed
export const mockActivities: ActivityItem[] = [
  {
    id: 'act-1',
    type: 'pledge',
    title: 'New pledge received',
    description: 'PayFlow Africa received a ₳5,000 pledge',
    projectId: 'proj-1',
    timestamp: '2024-09-12T14:30:00Z',
  },
  {
    id: 'act-2',
    type: 'stage_change',
    title: 'Project advanced',
    description: 'HealthBridge moved to Fundraising stage',
    projectId: 'proj-3',
    timestamp: '2024-09-10T09:00:00Z',
  },
  {
    id: 'act-3',
    type: 'hackathon_win',
    title: 'Hackathon winner',
    description: 'SolarGrid won 2nd place at Green Innovation Summit',
    projectId: 'proj-5',
    timestamp: '2024-08-01T18:00:00Z',
  },
  {
    id: 'act-4',
    type: 'project_update',
    title: 'Milestone reached',
    description: 'EduPesa hit 2,800 active users',
    projectId: 'proj-4',
    timestamp: '2024-09-05T12:00:00Z',
  },
  {
    id: 'act-5',
    type: 'team_join',
    title: 'Team expanded',
    description: 'Sarah Wanjiku joined HealthBridge team',
    projectId: 'proj-3',
    userId: 'user-8',
    timestamp: '2024-08-15T10:00:00Z',
  },
];
